server:
  port: 8001
spring:
  datasource:
    url: jdbc:mysql://192.168.67.132:3307/ubuntu_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: docker_mysql8
    driver-class-name: com.mysql.cj.jdbc.Driver
    initial-size: 1
    min-idle: 1
    max-active: 20
    max-wait: 60000
mybatis:
  mapper-locations: classpath:mapper/*.xml
